
name: BTCinC - Extend Blockchain

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  extend-chain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project (C89)
        run: make

      - name: Run BTCinC
        run: ./btcinc

      - name: Auto commit new block
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Extend blockchain"
          file_pattern: blocks/*.dat

